print('Глеб', end= ' ')
print('22',end= ' ')
print('Днипро',end= ' ')
print('-----------------------------')
sym = input('введите символ')
a = input('строка 1',)
b = input('строка 2',)
c = input('строка 3',)
print(a, end = sym)
print(b, end = sym)
print(c)